Tshop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from Tshop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import home,cart,OrderListView,checkout,LoginView,Signup,Signout,add_to_cart
from store.views.cart import add_to_cart
from store.views.contactus import contactus
from store.views import validatePayment, ProductDetailView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('',home),
    path('home/', home , name='homepage'),
    path('cart/', cart),
    path('orders/',login_required(OrderListView.as_view(), login_url='/Login/'), name ='orders'),
    path('Login/', LoginView.as_view(), name='login'),
    path('Logout/', Signout),
    path('checkout/', checkout),
    path('Signup/', Signup),
    path('product/<str:slug>',ProductDetailView.as_view()),
    path('addtocart/<str:slug>/<str:size>', add_to_cart),
    path('contactus/',contactus),
    path('validate_payment', validatePayment)

]

store/models/order.py
from django.db import models
from django.contrib.auth.models import User
from .tshirt import Tshirt
from .size import SizeVariant

class Order(models.Model):
    orderStatus = (
        ('PENDING', "Pending"),
        ('PLACED', "Placed"),
        ('CANCELLED', "Cancelled"),
        ('COMPLETED', "Completed"),
    )

    method = (
        ('COD', "Cod"),
        ('ONLINE', "Online")
    )
    order_status = models.CharField(max_length=15, choices=orderStatus)
    payment_method = models.CharField(max_length=15, choices=method)
    shipping_address = models.CharField(max_length=100, null = False)
    phone = models.CharField(max_length=10, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.IntegerField(null=False)
    date = models.DateTimeField(null=False, auto_now_add=True )
    
class OrderItem(models.Model):
    
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    tshirt = models.ForeignKey(Tshirt, on_delete = models.CASCADE)
    size = models.ForeignKey(SizeVariant, on_delete = models.CASCADE)
    quantity = models.IntegerField(null=False)
    price = models.IntegerField(null=False)
    date = models.DateTimeField(null=False, auto_now_add=True )
        
  

store/models/size.py
from django.db import models

from .tshirt import Tshirt

class SizeVariant(models.Model):
    SIZES = (
        ('S', "SMALL"),
        ('M', "MEDIUM"),
        ('L', "LARGE"),
        ('XL', "EXTRA LARGE"),
        ('XXL', "EXTRA EXTRA LARGE"),
    )
    price = models.IntegerField(null = False)
    tshirt = models.ForeignKey(Tshirt , on_delete = models.CASCADE)
    size = models.CharField(choices=SIZES ,max_length=5)

    def __str__(self):
        return f'{self.size}'

store/forms/authforms.py
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class CustomerAuthForm(AuthenticationForm):
    username = forms.CharField(required=True, label="Email")


class CustomerCreationForm(UserCreationForm):
    username = forms.CharField(required=True, label="Email")
    first_name = forms.CharField(required=True, label="First Name")
    last_name = forms.CharField(required=True, label="Last Name")

    def clean_first_name(self):
        value = self.cleaned_data.get('first_name')
        if len(value.strip()) < 4:
            raise ValidationError("First Name must be 4 characters long....")
        return value.strip()
    
    def clean_last_name(self):
        value = self.cleaned_data.get('last_name')
        if len(value.strip()) < 2:
            raise ValidationError("Last Name must be 2 characters long..")
        return value.strip()
       

    class Meta:
        model = User
        fields=['username','first_name','last_name']

store/views/authentication.py
from django.shortcuts import render,redirect
from store.forms.authforms import CustomerCreationForm , CustomerAuthForm
from django.contrib.auth import authenticate , login as loginUser ,logout
from store.models import SizeVariant, Cart
from django.views.generic.base import View

class LoginView(View):
    def get(self, request):
        form = CustomerAuthForm()
        next_page = request.GET.get('next')
        if next_page is not None:
            request.session['next_page']= next_page 
        return render(request , template_name='store/Login.html' , context = {'form':form} )

    def post(self, request):
        form = CustomerAuthForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username , password = password)
            if user:
                loginUser(request , user)
                session_cart = request.session.get('cart')
                if session_cart is None:
                    session_cart=[]
                    
                else:
                    for c in session_cart:
                        size = c.get('size')
                        quantity = c.get('quantity')
                        tshirt_id = c.get('tshirt')
                        cart_obj = Cart()
                        cart_obj.sizeVariant = SizeVariant.objects.get(size=size, tshirt=tshirt_id)
                        cart_obj.quantity = quantity
                        cart_obj.user = user
                        cart_obj.save()

                cart = Cart.objects.filter(user=user)
                session_cart = []
                for c in cart:
                    obj={
                        'size':c.sizeVariant.size,
                        'tshirt':c.sizeVariant.tshirt.id,
                        'quantity' : c.quantity
                    }
                    session_cart.append(obj)
                
                request.session['cart'] = session_cart
                next_page = request.session.get('next_page')
                if next_page is None:
                    next_page = 'homepage'

                return redirect(next_page)

        else:
            return render(request , template_name='store/Login.html' , context = {'form':form} )





def Signup(request):
    if(request.method == 'GET'):
        form = CustomerCreationForm()
        context = {
            "form": form
        }
        return render(request , template_name='store/Signup.html' , context=context)
    else:
        form = CustomerCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            user.email = user.username
            user.save()
            print(user)
            return redirect('login')
        context = {
            "form": form
         }
        return render(request , template_name='store/Signup.html' , context=context)
        

def Signout(request):
    logout(request)
    return render(request,template_name='store/home.html' )

store/views/cart.py
from django.shortcuts import render, redirect
from store.models import SizeVariant, Tshirt, Cart



def cart(request):
    cart = request.session.get('cart')
    if cart is None:
        cart=[]
    for c in cart:
        tshirt_id = c.get('tshirt')
        tshirt= Tshirt.objects.get(id=tshirt_id)
        c['size'] = SizeVariant.objects.get(tshirt=tshirt_id, size=c['size'])
        c['tshirt'] = tshirt
    
    
    return render(request , template_name='store/cart.html' ,context = {'cart':cart})


def add_to_cart(request, slug, size):
    user = None
    if request.user.is_authenticated:
        user=request.user

    cart = request.session.get('cart')
    
    if cart is None:
        cart = []
    tshirt = Tshirt.objects.get(slug=slug)
    add_cart_for_anom_user(cart,size,tshirt)

    if user is not None:
       add_cart_to_database(user,size,tshirt)

    request.session['cart'] = cart
    return_url = request.GET.get('return_url')
    return redirect(return_url)



    
def add_cart_to_database(user, size, tshirt):
        size = SizeVariant.objects.get(size=size, tshirt =tshirt)
        existing = Cart.objects.filter(user=user, sizeVariant = size)
        if len(existing) > 0:
            obj = existing[0]
            obj.quantity = obj.quantity+1
            obj.save()

        else:
            c = Cart()
            c.user = user
            c.sizeVariant = size
            c.quantity = 1
            c.save()


def add_cart_for_anom_user(cart, size, tshirt):
    flag = True
    for cart_obj in cart:
        t_id = cart_obj.get('tshirt')
        size_short = cart_obj.get('size')
        if t_id == tshirt.id and size==size_short:
            flag=False
            cart_obj['quantity'] = cart_obj['quantity']+1
    if flag:
        cart_obj ={
            'tshirt': tshirt.id,
            'size':size,
            'quantity': 1
            
        }
        cart.append(cart_obj)

store/views/checkout.py
from django.shortcuts import render,redirect
from store.models import Order,SizeVariant,OrderItem, Payment
from math import floor
from django.contrib.auth.decorators import login_required
from store.forms.checkout_form import CheckForm
from Tshop.settings import API_KEY, AUTH_TOKEN
from instamojo_wrapper import Instamojo
API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/');



def cal_total_payable_amount(cart):
     total=0
     for c in cart:
          discount = c.get('tshirt').discount
          price=c.get('size').price
          sale_price = floor(price - (price * (discount/100)))
          total_of_single_product = sale_price * c.get('quantity')
          total = total + total_of_single_product
     
     return total

@login_required(login_url ='/Login/')
def checkout(request):
    #get Request
    if request.method == 'GET':
        form = CheckForm()
        cart=request.session.get('cart')
        if cart is None:
            cart=[]
    
        for c in cart:
            size_str = c.get('size')
            tshirt_id= c.get('tshirt')
            size_obj = SizeVariant.objects.get(size=size_str, tshirt= tshirt_id)
            c['size'] = size_obj
            c['tshirt'] = size_obj.tshirt
        return render(request, 'store/checkout.html',{"form":form, 'cart':cart})
    else:
        #post request
        form = CheckForm(request.POST)
        user = None
        if request.user.is_authenticated:
            user= request.user

        if form.is_valid():
            #payment
            cart = request.session.get('cart')
            if cart is None:
                cart=[]
            
            for c in cart:
                size_str = c.get('size')
                tshirt_id= c.get('tshirt')
                size_obj = SizeVariant.objects.get(size=size_str, tshirt= tshirt_id)
                c['size'] = size_obj
                c['tshirt'] = size_obj.tshirt

            shipping_address = form.cleaned_data.get('shipping_address')
            phone = form.cleaned_data.get('phone')
            payment_method = form.cleaned_data.get('payment_method')
            total = cal_total_payable_amount(cart)
            print(shipping_address, phone, payment_method, total)
            order = Order()
            order.shipping_address = shipping_address
            order.phone = phone
            order.payment_method = payment_method
            order.total = total
            order.order_status = "PENDING"
            order.user = user
            order.save()
            

            #order items saving
            for c in cart:
                order_item =  OrderItem()
                order_item.order = order
                size= c.get('size')
                tshirt= c.get('tshirt')
                order_item.price = floor(size.price - (size.price * (tshirt.discount/100) ))
                order_item.quantity = c.get('quantity')
                order_item.size =size
                order_item.tshirt = tshirt
                order_item.save()


            #creating payment

            response = API.payment_request_create(
            amount=order.total,
            purpose="Payment for Tshirts",
            send_email=True,
            buyer_name = f'{user.first_name} {user.last_name}',
            email=user.email,
            redirect_url="http://localhost:8000/validate_payment"
            )

            payment_request_id = response['payment_request']['id']
            url = response['payment_request']['longurl']
            payment = Payment()
            payment.order =order
            payment.payment_request_id = payment_request_id
            payment.save()

            return redirect(url)
        
        else:
            return redirect('/checkout/')
        

store/views/contactus.py
from django.shortcuts import render

def contactus(request):
    return render(request,template_name="store/contactus.html")

store/views/home.py
from store.models import Occassion,Brand,Color,IdealFor,NeckType,Sleeve ,Tshirt
from django.core.paginator import  Paginator
from django.shortcuts import render
from urllib.parse import urlencode
def home(request):
    query = request.GET
    tshirts = []
    tshirts = Tshirt.objects.all()

    
    brand = query.get('brand')
    neckType = query.get('necktype')
    color = query.get('color')
    occassion = query.get('occassion')
    idealfor = query.get('idealfor')
    sleeve = query.get('sleeve')
    page = query.get('page')

    if(page is None or page == ''):
        page = 1


    if brand !='' and brand is not None:
        tshirts = tshirts.filter(brand__slug = brand)
    
    if neckType!='' and neckType is not None:
        tshirts = tshirts.filter(necktype__slug = neckType)
    
    if color!='' and color is not None:
        tshirts = tshirts.filter(color__slug = color)

    if occassion !='' and occassion is not None:
        tshirts = tshirts.filter(occassion__slug = occassion)

    if idealfor !='' and idealfor is not None:
        tshirts = tshirts.filter(idealfor__slug = idealfor)
    
    if sleeve!='' and sleeve is not None:
        tshirts = tshirts.filter(sleeve__slug = sleeve)


    

    occassions = Occassion.objects.all()
    brands = Brand.objects.all()
    sleeves = Sleeve.objects.all()
    idealFor = IdealFor.objects.all()
    neckTypes = NeckType.objects.all()
    colors = Color.objects.all()


    paginator = Paginator(tshirts, 3)
    page_object = paginator.get_page(page)

    query = request.GET.copy()
    query['page'] = ''
    pageurl = urlencode(query)
    
    
    context ={
        "page_obj": page_object,
        "occassions":occassions,
        "brands":brands,
        "colors": colors,
        "sleeves":sleeves,
        "neckTypes":neckTypes,
        "idealFor":idealFor,
        "pageurl":pageurl
    }
    return render(request , template_name='store/home.html', context = context)

store/views/orders.py
from store.models import Order
from django.views.generic.list import ListView




     
class OrderListView(ListView):
    template_name = 'store/orders.html'
    model = Order
    context_object_name = 'orders'
    paginate_by = 5
    def get_queryset(self):
        return Order.objects.filter(user = self.request.user).order_by('-date').exclude(order_status='PENDING')

store/views/payment.py
from store.models import  Cart, Payment
from django.shortcuts import render,redirect
from Tshop.settings import API_KEY, AUTH_TOKEN
from instamojo_wrapper import Instamojo
API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/');


def validatePayment(request):
    user = None
    if request.user.is_authenticated:
        user = request.user

    payment_request_id = request.GET.get('payment_request_id')
    payment_id = request.GET.get('payment_id')
    response = API.payment_request_payment_status(payment_request_id, payment_id)
    status = response.get('payment_request').get('payment').get('status')

    if status != "Failed":
        print("Payment Success")
        try:
            payment = Payment.objects.get(payment_request_id = payment_request_id)
            payment.payment_id = payment_id
            payment.payment_status = status
            payment.save()

            order = payment.order
            order.order_status = 'PLACED'
            order.save()
             
            cart =[]
            request.session['cart'] = cart

            Cart.objects.filter(user = user).delete()
            return redirect('orders')
        except:
            
            
            return render(request, 'store/payment_failed.html')


    else:
        
        #return error page
        return render(request, 'store/payment_failed.html')
    

store/views/product_page.py
from store.models import  Tshirt
from math import floor
from django.views.generic.detail import DetailView

class ProductDetailView(DetailView):
    template_name ='store/product_details.html'
    model = Tshirt
    
    def get_context_data(self, **kwargs): 
        context =  super().get_context_data(**kwargs)
        tshirt =context.get('tshirt')
        request = self.request
        size=request.GET.get('size')
        if size is None:
            size=tshirt.sizevariant_set.all().order_by('price').first()
        else:
            size=tshirt.sizevariant_set.get(size=size)
        size_price=floor(size.price)
        sell_price=floor(size_price-(size_price*(tshirt.discount/100)))
        context={'tshirt':tshirt, 'price':size_price ,'sell_price':sell_price,'active_size':size}
   
        return context

store/templates/store/Login.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    

    body{
        background-image: url("https://c1.wallpaperflare.com/preview/208/6/435/shop-t-shirt-clothes-t-shirts.jpg");
        background-size: cover;

    }

    .div1 {
        background-color: aliceblue;
    }
</style>


<div class="col-lg-4 mx-auto border rounded p-3 mt-4 div1">
    <form action="/Login/" method="post">
        {% csrf_token %}
        <h1 class="display-4 text-center">Login Here</h1>

        <div class="text-center">
            <img height=80px src="http://clipart-library.com/data_images/109931.png" alt="">
        </div>
        <hr>
        {{ form|crispy }}

        <br>
        <div class="form-group">
            <input class="btn btn-info " type="submit" value="Login">
        </div>
    </form>
</div>


{% endblock %}

store/templates/store/Signup.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    body{
        background-image: url("https://c1.wallpaperflare.com/preview/208/6/435/shop-t-shirt-clothes-t-shirts.jpg");
        background-size: cover;

    }
    .div1 {
        background-color: aliceblue;
    }
</style>

<div class="col-lg-4 mx-auto border rounded p-4 mt-4 div1">
    <form action="/Signup/" method="post">
        {% csrf_token %}
        <h1 class="display-4">Create Account</h1>
        <hr>
        {{form|crispy}}
       
        <div class="form-group" >
            <input class="btn btn-info" type="submit" value="Create Account">
        </div>
    </form>
</div>
{% endblock %}

store/templates/store/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Tshirt_shop</title>
    <style>
        .display-6{
            font-size: 30px;
            font-weight: 300;
        }
        .display-8{
            font-size: 20px;
            font-weight: 300;
        }
    </style>
</head>

<body>
    <!--Navbar start-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">


        <div class="container-fluid">
            <img height="45px" class="rounded-circle" src="https://www.linkpicture.com/q/1_72.jpeg"  alt="">
            <a class="navbar-brand" href="/" ><strong><em>&nbsp;ShirtIsta</strong></em></a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/cart">Cart&nbsp;<span class="badge badge-info">{{request.session.cart|length}}</span></a>
                    </li>

                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/orders">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Logout">Logout</a>
                    </li>

                    {% else %}

                   
                    
                    <li class="nav-item">
                        <a class="nav-link" href="/Login">Login</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="/Signup">SignUp</a>

                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link text-white" href="/contactus">Contact Us </a>
                    </li> 
                </ul>

            </div>
        </div>
    </nav>
    <!--Navbar End-->
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

store/templates/store/cart.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% block content %}
<div class="container">
    <div>
        <table class="table table-hover table-stripped">
            <thread>
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Tshirt</th>
                    <th>Size</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Sale Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thread>
            <tbody>
                {% for c in cart %}

                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img height="70px" class="img rounded-circle" src={{c.tshirt.image.url}} /></td>
                    <td>{{c.tshirt.name}}</td>
                    <td>{{c.size.size}}</td>
                    <td>{{c.size.price|rupee}}</td>
                    <td>{{c.tshirt.discount}}%</td>
                    <td>{% clc_sale_price c.size.price c.tshirt.discount as sale_price %}{{sale_price|rupee}}</td>
                    <td>{{c.quantity}}</td>
                    <td>{% multiply c.quantity sale_price as total %}{{total|rupee}}</td>
                </tr>
                {% endfor %}
            <tfoot>
                <tr>
                    <th colspan="3"></th>
                    <th colspan="5">PAYABLE AMOUNT</th>
                    <th>{{cart|cal_total_payable_amount|rupee}}</th>

                </tr>
                <tr>
                  <th colspan="7"></th>
                    <th colspan="2"><a href="/checkout" class="btn btn-outline-dark">Continue to Checkout</button></th>

                </tr>

            </tfoot>
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

store/templates/store/checkout.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% load tshirt_tags %}
{% block content %}
<div class="container">
    <div class="p-2">
        <div class="display-6">Checkout Page</div>
        <hr>
        <div class="row">
            <div class="col-lg-5 border rounded p-3">
                <form action="/checkout/" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    &nbsp;
                    <hr>
                    <div class="form-group">
                        <input type="submit" value="Checkout" class="btn btn-outline-dark">
                    </div>
                </form>
            </div>
            <div class="col">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tshirt</th>
                            <th>Size</th>
                            <th>Quantity</th>
                            <th>Price After Discount</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cart %}
                        <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{c.size.tshirt.name}}</td>
                        <td>{{c.size.size}}</td> 
                        <td>{{c.quantity}}</td>
                        <td>{% clc_sale_price c.size.price c.size.tshirt.discount  as sale_price %}{{sale_price|rupee}}</td> 
                        <td>{% multiply c.quantity sale_price as total%}{{total|rupee}}</td>
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <hr>
                <div>
                    <div class="display-6 alert">Total Payable Amount : {{cart|cal_total_payable_amount|rupee}}</div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

store/templates/store/contactus.html
{% extends "./base.html" %}
{% load crispy_forms_tags %}    <! crispy form for bootstrap effect >


{% block content%}
<!--

//-->
<div class="text-center">
  <img height="300px"  class="m-5"  src="https://www.linkpicture.com/q/bgtshirt.jpg" alt="">
</div>
<div class="text-center">
  <p><strong><em>ShirtIsta- A T-shop Company Limited</strong></em></p>
</div>
<div>
  <h3 class="p-1 mb-1 bg-danger text-white text-center">Store Address:</h3>
  <h5 class="lead text-center"><span><strong><em>No.3 9th MAIN 2nd CROSS, <br>GB Palya Road, NEAR ICICI ATM, Jayanagar,<br> Bengaluru, Karnataka 560041</span></h5>
  </em></strong><br>
  <h4 style="color:rgb(67, 48, 240);" class="lead text-center "><span><strong>WORKING HOURS : 10AM - 9PM (ALL DAYS)</strong></span></h4>
  <h4 style="color:#ffffff;" class="lead text-center btn-success "><span><strong>Contact : 8792437224</strong></span></h4>
  <h6 class="lead text-center">Email: shirtista@gmail.com </h6>
</div>
<br>



{% endblock %}

store/templates/store/orders.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% load order_tags %}
{% block content %}

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Items</th>
                <th>Grand Total</th>
                <th>Status</th>
            </tr>

        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.date|date}}</td>
                <td>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Tshirt</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for oi in order.orderitem_set.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><img height="60px" class="border" src={{oi.tshirt.image.url}} alt=""></td>
                                <td>{{oi.tshirt.name}}</td>
                                <td>{{oi.price|rupee}}</td>
                                <td>{{oi.quantity}}</td>
                                <td>{% multiply oi.quantity oi.price as total%}{{total|rupee}}</td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
                <td>
                    <span>{{order.total|rupee}}</span>
                    
                </td>
                
                <td>
                     
                    <span class="badge badge-{% get_order_status_class order.order_status %}">{{order.order_status}}</span>
                    
                </td>
                

            </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation" class="mt-2">
        <ul class="pagination justify-content-end">
          {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?{{pageurl}}">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
    
            <li class="page-item">
                <a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
            </li>
    
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
        </ul>
      </nav>
      
</div>


{% endblock %}

store/templates/store/payment_failed.html
{% extends "./base.html" %}

{% block content %}
<br>
<br>
<div class="jumbotron container p-2 alert alert-danger text-center">
    <h1 class="display-4">Payment Failed</h1>
    
    <hr class="my-4">
    <p>Your payment failed, if any money deducted from your bank account will be credited within 5 to 10 working days.</p>
</div>

{% endblock %}